# Generated by Django 5.0.2 on 2024-03-26 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 19, 55, 25, 891239, tzinfo=datetime.timezone.utc)),
        ),
    ]
