# Generated by Django 5.0.2 on 2024-02-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0002_remove_tournament_matches_remove_score_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedcommand',
            name='invitedReason',
            field=models.TextField(null=True),
        ),
    ]
