# Generated by Django 5.0.3 on 2024-03-27 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0003_rename_profilepicture_user_avatarpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 16, 6, 14, 536976, tzinfo=datetime.timezone.utc)),
        ),
    ]
