# Generated by Django 5.0.2 on 2024-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0004_rename_invitedcommand_channelorfriendcommand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChannelOrFriendCommand',
            new_name='ChannelOrFriendInvitedCommand',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(related_name='game_users', to='backendApi.user'),
        ),
    ]
