# Generated by Django 5.0.3 on 2024-03-27 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0004_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedcommand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invitedcommand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mutedcommand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 21, 31, 24, 363612, tzinfo=datetime.timezone.utc)),
        ),
    ]
