# Generated by Django 5.0.2 on 2024-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0005_rename_channelorfriendcommand_channelorfriendinvitedcommand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public'),
        ),
        migrations.AlterField(
            model_name='channelorfriendinvitedcommand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('tournament', 'Tournament')], default='normal'),
        ),
        migrations.AlterField(
            model_name='game',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
