# Generated by Django 5.0.2 on 2024-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0008_alter_user_id42_alter_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
