# Generated by Django 5.0.2 on 2024-02-13 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0010_alter_user_managers_alter_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedcommand',
            name='bannedReason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mutedcommand',
            name='mutedReason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bannedcommand',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='bannedcommand',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='channelorfriendinvitedcommand',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='channelorfriendinvitedcommand',
            name='invitedReason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
