# Generated by Django 5.0.2 on 2024-02-13 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0012_channel_banneds_channel_inviteds_channel_muteds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 10, 48, 652821, tzinfo=datetime.timezone.utc)),
        ),
    ]
