# Generated by Django 5.0.2 on 2024-02-13 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0013_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 38, 45, 666043, tzinfo=datetime.timezone.utc)),
        ),
    ]
