# Generated by Django 5.0.2 on 2024-02-13 17:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0015_alter_channel_banneds_alter_channel_inviteds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(default=[], related_name='channel_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banneds',
            field=models.ManyToManyField(default=[], related_name='channel_banneds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='inviteds',
            field=models.ManyToManyField(related_name='channel_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='muteds',
            field=models.ManyToManyField(default=[], related_name='channel_muteds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 56, 52, 678868, tzinfo=datetime.timezone.utc)),
        ),
    ]
