# Generated by Django 5.0.2 on 2024-02-13 17:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0016_alter_channel_admins_alter_channel_banneds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(related_name='channel_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banneds',
            field=models.ManyToManyField(related_name='channel_banneds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='muteds',
            field=models.ManyToManyField(related_name='channel_muteds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 17, 58, 43, 945251, tzinfo=datetime.timezone.utc)),
        ),
    ]
