# Generated by Django 5.0.2 on 2024-02-13 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0017_alter_channel_admins_alter_channel_banneds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 18, 2, 41, 402272, tzinfo=datetime.timezone.utc)),
        ),
    ]
