# Generated by Django 5.0.2 on 2024-02-13 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0018_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 18, 6, 9, 955267, tzinfo=datetime.timezone.utc)),
        ),
    ]
