# Generated by Django 5.0.2 on 2024-02-17 10:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0023_alter_channel_banneds_alter_channel_inviteds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='bannedcommand',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='bannedcommand',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel'),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 10, 11, 14, 908047, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='InvitedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=100)),
                ('invitedReason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApi.channel')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelOrFriendInvitedCommand',
        ),
    ]
