# Generated by Django 5.0.2 on 2024-02-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0024_remove_user_friends_alter_bannedcommand_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 10, 13, 10, 589151, tzinfo=datetime.timezone.utc)),
        ),
    ]
