# Generated by Django 5.0.2 on 2024-02-17 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0025_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstConnection',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id42',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiration',
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 10, 19, 51, 133020, tzinfo=datetime.timezone.utc)),
        ),
    ]
