# Generated by Django 5.0.2 on 2024-02-18 09:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0027_alter_mutedcommand_until_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 9, 54, 34, 556255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
