# Generated by Django 5.0.2 on 2024-02-18 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0028_alter_mutedcommand_until_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 10, 15, 56, 230558, tzinfo=datetime.timezone.utc)),
        ),
    ]
