# Generated by Django 5.0.2 on 2024-02-18 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0029_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='_secretKey',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='secretKey',
        ),
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 10, 46, 57, 538342, tzinfo=datetime.timezone.utc)),
        ),
    ]
