# Generated by Django 5.0.2 on 2024-02-18 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0031_rename__secretkey_otp_secretkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 35, 27, 237078, tzinfo=datetime.timezone.utc)),
        ),
    ]
