# Generated by Django 5.0.2 on 2024-02-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0032_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 10, 39, 38, 75626, tzinfo=datetime.timezone.utc)),
        ),
    ]
