# Generated by Django 5.0.2 on 2024-03-25 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0033_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 11, 48, 16, 597281, tzinfo=datetime.timezone.utc)),
        ),
    ]
