# Generated by Django 5.0.2 on 2024-03-25 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApi', '0035_alter_mutedcommand_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutedcommand',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 15, 46, 9, 451262, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=100),
        ),
    ]
